//! パレットを支える静的なコマンドテーブル。実行可能なコマンド 1 つにつき
//! 1 エントリで、カテゴリごとにまとめてある。

use super::types::{CommandCategory, CommandId, PaletteCommand};
use crate::keymap::Action;

pub const COMMANDS: &[PaletteCommand] = &[
    // Navigation
    PaletteCommand {
        id: CommandId::FocusWorktree,
        label: "Focus: Worktree Panel",
        category: CommandCategory::Navigation,
        action: Some(Action::FocusWorktree),
        keywords: "panel switch",
    },
    PaletteCommand {
        id: CommandId::FocusExplorer,
        label: "Focus: Explorer Panel",
        category: CommandCategory::Navigation,
        action: Some(Action::FocusExplorer),
        keywords: "panel files",
    },
    PaletteCommand {
        id: CommandId::FocusViewer,
        label: "Focus: Viewer Panel",
        category: CommandCategory::Navigation,
        action: Some(Action::FocusViewer),
        keywords: "panel file view",
    },
    PaletteCommand {
        id: CommandId::FocusTerminalClaude,
        label: "Focus: Claude Code Terminal",
        category: CommandCategory::Navigation,
        action: Some(Action::FocusTerminalClaude),
        keywords: "terminal claude",
    },
    PaletteCommand {
        id: CommandId::FocusTerminalShell,
        label: "Focus: Shell Terminal",
        category: CommandCategory::Navigation,
        action: Some(Action::FocusTerminalShell),
        keywords: "terminal shell",
    },
    PaletteCommand {
        id: CommandId::NextWorktree,
        label: "Next Worktree",
        category: CommandCategory::Navigation,
        action: Some(Action::NextWorktree),
        keywords: "worktree switch next cycle tab",
    },
    PaletteCommand {
        id: CommandId::PrevWorktree,
        label: "Previous Worktree",
        category: CommandCategory::Navigation,
        action: Some(Action::PrevWorktree),
        keywords: "worktree switch previous cycle tab",
    },
    PaletteCommand {
        id: CommandId::TogglePanelExpand,
        label: "Toggle Panel Expand",
        category: CommandCategory::Navigation,
        action: Some(Action::TogglePanelExpand),
        keywords: "resize maximize fullscreen",
    },
    PaletteCommand {
        id: CommandId::ResizePaneLeft,
        label: "Layout: Resize Pane Left",
        category: CommandCategory::Navigation,
        action: Some(Action::ResizePaneLeft),
        keywords: "resize pane panel width column shrink grow tmux left",
    },
    PaletteCommand {
        id: CommandId::ResizePaneRight,
        label: "Layout: Resize Pane Right",
        category: CommandCategory::Navigation,
        action: Some(Action::ResizePaneRight),
        keywords: "resize pane panel width column shrink grow tmux right",
    },
    PaletteCommand {
        id: CommandId::ResizePaneUp,
        label: "Layout: Resize Pane Up",
        category: CommandCategory::Navigation,
        action: Some(Action::ResizePaneUp),
        keywords: "resize pane panel height shell claude split shorter taller tmux up",
    },
    PaletteCommand {
        id: CommandId::ResizePaneDown,
        label: "Layout: Resize Pane Down",
        category: CommandCategory::Navigation,
        action: Some(Action::ResizePaneDown),
        keywords: "resize pane panel height shell claude split shorter taller tmux down",
    },
    // Worktree
    PaletteCommand {
        id: CommandId::CreateWorktree,
        label: "Worktree: Create New",
        category: CommandCategory::Worktree,
        action: Some(Action::CreateWorktree),
        keywords: "branch new add",
    },
    PaletteCommand {
        id: CommandId::DeleteWorktree,
        label: "Worktree: Delete Selected",
        category: CommandCategory::Worktree,
        action: Some(Action::DeleteWorktree),
        keywords: "remove branch",
    },
    PaletteCommand {
        id: CommandId::SwitchBranch,
        label: "Worktree: Switch Branch (Remote)",
        category: CommandCategory::Worktree,
        action: Some(Action::SwitchBranch),
        keywords: "checkout remote",
    },
    PaletteCommand {
        id: CommandId::GrabBranch,
        label: "Worktree: Grab Branch",
        category: CommandCategory::Worktree,
        action: Some(Action::GrabBranch),
        keywords: "grab checkout branch",
    },
    PaletteCommand {
        id: CommandId::PruneWorktrees,
        label: "Worktree: Prune Stale",
        category: CommandCategory::Worktree,
        action: Some(Action::PruneWorktrees),
        keywords: "clean stale",
    },
    PaletteCommand {
        id: CommandId::MergeToMain,
        label: "Worktree: Merge into Main",
        category: CommandCategory::Worktree,
        action: Some(Action::MergeToMain),
        keywords: "merge main",
    },
    PaletteCommand {
        id: CommandId::RefreshWorktrees,
        label: "Worktree: Refresh List",
        category: CommandCategory::Worktree,
        action: Some(Action::RefreshWorktrees),
        keywords: "reload update",
    },
    PaletteCommand {
        id: CommandId::ResetMainToOrigin,
        label: "Worktree: Reset Main to Origin",
        category: CommandCategory::Worktree,
        action: Some(Action::ResetMainToOrigin),
        keywords: "reset origin",
    },
    PaletteCommand {
        id: CommandId::CherryPick,
        label: "Worktree: Cherry-pick",
        category: CommandCategory::Worktree,
        action: Some(Action::CherryPick),
        keywords: "cherry pick commit",
    },
    PaletteCommand {
        id: CommandId::PullWorktree,
        label: "Worktree: Pull (fast-forward)",
        category: CommandCategory::Worktree,
        action: Some(Action::PullWorktree),
        keywords: "pull fetch update fast-forward ff sync",
    },
    // Worktree (追加分)
    PaletteCommand {
        id: CommandId::UngrabBranch,
        label: "Worktree: Ungrab Branch",
        category: CommandCategory::Worktree,
        action: Some(Action::UngrabBranch),
        keywords: "ungrab release branch",
    },
    // Terminal
    PaletteCommand {
        id: CommandId::NewClaudeCode,
        label: "Terminal: New Claude Code",
        category: CommandCategory::Terminal,
        action: Some(Action::NewClaudeCode),
        keywords: "spawn ai",
    },
    PaletteCommand {
        id: CommandId::NewShell,
        label: "Terminal: New Shell",
        category: CommandCategory::Terminal,
        action: Some(Action::NewShell),
        keywords: "spawn bash zsh",
    },
    PaletteCommand {
        id: CommandId::ResumeClaudeSession,
        label: "Terminal: Resume Claude Session",
        category: CommandCategory::Terminal,
        action: None,
        keywords: "resume continue",
    },
    // Git
    PaletteCommand {
        id: CommandId::RefreshDiff,
        label: "Diff: Refresh",
        category: CommandCategory::Git,
        action: None,
        keywords: "reload diff",
    },
    // View
    PaletteCommand {
        id: CommandId::SearchInFile,
        label: "Search in File",
        category: CommandCategory::View,
        action: Some(Action::SearchInFile),
        keywords: "find grep",
    },
    PaletteCommand {
        id: CommandId::SearchFullText,
        label: "Search: Full-text Search (Grep)",
        category: CommandCategory::View,
        action: Some(Action::SearchFullText),
        keywords: "grep search find text content regex ripgrep fulltext",
    },
    PaletteCommand {
        id: CommandId::ToggleMarkdownRender,
        label: "Viewer: Toggle Markdown Raw / Rendered",
        category: CommandCategory::View,
        action: Some(Action::ToggleMarkdownRender),
        keywords: "markdown md render raw preview prose readme",
    },
    PaletteCommand {
        id: CommandId::ToggleHelp,
        label: "Show Help",
        category: CommandCategory::View,
        action: Some(Action::ShowHelp),
        keywords: "keybindings shortcuts",
    },
    PaletteCommand {
        id: CommandId::ShowDiffList,
        label: "Explorer: Show Diff List",
        category: CommandCategory::View,
        action: Some(Action::ShowDiffList),
        keywords: "diff changed files",
    },
    PaletteCommand {
        id: CommandId::ShowCommentList,
        label: "Explorer: Show Comment List",
        category: CommandCategory::View,
        action: Some(Action::ShowCommentList),
        keywords: "comment review list",
    },
    PaletteCommand {
        id: CommandId::ShowWalkthrough,
        label: "Review: Show Walkthrough",
        category: CommandCategory::View,
        action: Some(Action::ShowWalkthrough),
        keywords: "walkthrough steps ai tour",
    },
    // Review
    PaletteCommand {
        id: CommandId::ShowReviewComments,
        label: "Review: Show Comments",
        category: CommandCategory::Review,
        action: None,
        keywords: "comment list",
    },
    PaletteCommand {
        id: CommandId::ShowReviewTemplates,
        label: "Review: Show Templates",
        category: CommandCategory::Review,
        action: None,
        keywords: "template prompt",
    },
    PaletteCommand {
        id: CommandId::SessionHistory,
        label: "Review: Session History",
        category: CommandCategory::Review,
        action: Some(Action::SessionHistory),
        keywords: "history log",
    },
    PaletteCommand {
        id: CommandId::ReviewPullRequest,
        label: "Review: Review Pull Request…",
        category: CommandCategory::Review,
        action: Some(Action::ReviewPullRequest),
        keywords: "pr pull request github fetch worktree walkthrough number url",
    },
    PaletteCommand {
        id: CommandId::GenerateWalkthrough,
        label: "Review: Generate Walkthrough",
        category: CommandCategory::Review,
        action: Some(Action::GenerateWalkthrough),
        keywords: "walkthrough tour generate ai claude steps regenerate retry",
    },
    PaletteCommand {
        id: CommandId::ForceGenerateWalkthrough,
        label: "Review: Regenerate Walkthrough (force)",
        category: CommandCategory::Review,
        action: Some(Action::ForceGenerateWalkthrough),
        keywords: "walkthrough regenerate force rebuild ignore cache same commit ai claude steps",
    },
    PaletteCommand {
        id: CommandId::PublishReview,
        label: "Review: Publish Comments to GitHub",
        category: CommandCategory::Review,
        action: Some(Action::PublishReview),
        keywords: "publish post github pr comments review upload",
    },
    PaletteCommand {
        id: CommandId::AddReviewComment,
        label: "Review: Add Comment",
        category: CommandCategory::Review,
        action: Some(Action::AddComment),
        keywords: "new comment add write",
    },
    PaletteCommand {
        id: CommandId::ViewCommentDetail,
        label: "Review: View Comment Detail",
        category: CommandCategory::Review,
        action: Some(Action::ViewCommentDetail),
        keywords: "detail preview",
    },
    PaletteCommand {
        id: CommandId::DeleteComment,
        label: "Review: Delete Comment",
        category: CommandCategory::Review,
        action: Some(Action::DeleteComment),
        keywords: "remove delete",
    },
    PaletteCommand {
        id: CommandId::ToggleCommentResolve,
        label: "Review: Toggle Resolve",
        category: CommandCategory::Review,
        action: Some(Action::ToggleResolve),
        keywords: "resolve unresolve status",
    },
    PaletteCommand {
        id: CommandId::EditComment,
        label: "Review: Edit Comment",
        category: CommandCategory::Review,
        action: Some(Action::EditComment),
        keywords: "edit modify update",
    },
    PaletteCommand {
        id: CommandId::ReplyToComment,
        label: "Review: Reply to Comment",
        category: CommandCategory::Review,
        action: Some(Action::ReplyToComment),
        keywords: "reply respond",
    },
    PaletteCommand {
        id: CommandId::SaveSessionHistory,
        label: "Session: Save History",
        category: CommandCategory::Review,
        action: None,
        keywords: "save record session",
    },
    // Repository
    PaletteCommand {
        id: CommandId::OpenRepo,
        label: "Repository: Open by Path",
        category: CommandCategory::Repository,
        action: Some(Action::OpenRepo),
        keywords: "open directory",
    },
    PaletteCommand {
        id: CommandId::SwitchRepo,
        label: "Repository: Switch",
        category: CommandCategory::Repository,
        action: Some(Action::SwitchRepo),
        keywords: "project change",
    },
    // GitHub / PR
    PaletteCommand {
        id: CommandId::OpenPullRequest,
        label: "Worktree: Open Pull Request",
        category: CommandCategory::Worktree,
        action: Some(Action::OpenPullRequest),
        keywords: "pr github browser web open",
    },
    // App
    PaletteCommand {
        id: CommandId::CheckForUpdate,
        label: "App: Check for Updates",
        category: CommandCategory::App,
        action: None,
        keywords: "update upgrade version check latest release new github",
    },
    PaletteCommand {
        id: CommandId::UpdateAndRestart,
        label: "App: Update and Restart",
        category: CommandCategory::App,
        action: None,
        keywords: "update upgrade restart download version",
    },
    PaletteCommand {
        id: CommandId::TogglePartyMode,
        label: "🎉 Party Mode (secret)",
        category: CommandCategory::App,
        action: None,
        keywords: "party rainbow fun secret celebration mode hidden festive disco",
    },
    PaletteCommand {
        id: CommandId::ToggleRichMode,
        label: "✨ Toggle Rich Mode",
        category: CommandCategory::App,
        action: None,
        keywords: "rich mode graphics gradient border glow visual effects truecolor",
    },
    PaletteCommand {
        id: CommandId::Quit,
        label: "Quit Conductor",
        category: CommandCategory::App,
        action: Some(Action::Quit),
        keywords: "exit close",
    },
    // UI
    PaletteCommand {
        id: CommandId::SwitchTheme,
        label: "Switch Theme",
        category: CommandCategory::View,
        action: Some(Action::OpenThemePicker),
        keywords: "theme color light dark appearance palette catppuccin solarized github",
    },
    PaletteCommand {
        id: CommandId::ToggleHighContrast,
        label: "UI: Toggle High Contrast",
        category: CommandCategory::View,
        action: None,
        keywords: "high contrast accessibility a11y legibility bright bold theme readable vision",
    },
];
