//! Small state types shared across `App`: status messages, worktree-list rows,
//! worktree input/operation state, view-restore bookkeeping, dirty-panel
//! tracking, and background-operation handles.

use std::path::PathBuf;
use std::sync::Arc;
use std::sync::atomic::AtomicBool;

use crate::background::BackgroundOp;
use crate::git_engine;

/// The severity/type of a status message, used for styling.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StatusLevel {
    Success,
    Error,
    Warning,
    Info,
}

/// A status message with metadata for styled, timed display.
#[derive(Debug, Clone)]
pub struct StatusMessage {
    /// The text content of the message.
    pub text: String,
    /// The severity level (determines color and icon).
    pub level: StatusLevel,
    /// The `ui_tick` at which this message was created.
    pub created_at_tick: u64,
}

impl StatusMessage {
    pub fn new(text: String, level: StatusLevel, tick: u64) -> Self {
        Self {
            text,
            level,
            created_at_tick: tick,
        }
    }

    /// Return the icon prefix for this message level.
    pub fn icon(&self) -> &'static str {
        match self.level {
            StatusLevel::Success => "\u{2713} ", // ✓
            StatusLevel::Error => "\u{2717} ",   // ✗
            StatusLevel::Warning => "\u{26A1} ", // ⚡
            StatusLevel::Info => "\u{2139} ",    // ℹ
        }
    }
}

impl From<String> for StatusMessage {
    fn from(text: String) -> Self {
        Self {
            text,
            level: StatusLevel::Info,
            created_at_tick: 0,
        }
    }
}

/// A row in the flattened worktree list (worktree headers + inline session rows).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorktreeListRow {
    /// A worktree entry at `worktrees[idx]`.
    Worktree(usize),
    /// A Claude Code session under a worktree.
    Session { wt_idx: usize, pty_idx: usize },
}

/// Input mode for worktree operations.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorktreeInputMode {
    /// Normal navigation.
    Normal,
    /// Typing a new worktree branch name (step 1 of create).
    CreatingWorktree,
    /// Typing a base branch for the new worktree (step 2 of create).
    CreatingWorktreeBase,
    /// Confirming worktree deletion (y/n).
    ConfirmingDelete,
    /// Confirming branch deletion after worktree removal (y/n/f).
    #[allow(dead_code)]
    ConfirmingDeleteBranch,
    /// Confirming ungrab (y/n).
    ConfirmingUngrab,
    /// Confirming a hard reset of main to origin (y/n) — discards local commits.
    ConfirmingReset,
    /// Smart Worktree: typing a multi-line task description.
    SmartDescription,
}

/// The kind of pending worktree background operation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PendingWorktreeOp {
    Creating,
    Deleting,
    /// Smart worktree: LLM generation + worktree creation running in background.
    SmartCreating,
}

/// A worktree operation currently running in a background thread.
#[derive(Debug, Clone)]
pub struct PendingWorktree {
    pub branch: String,
    pub op: PendingWorktreeOp,
    pub base_ref: String,
    pub worktree_path: Option<PathBuf>,
    pub auto_spawn: bool,
    pub smart_prompt: String,
    /// Session name for Claude Code `--name` flag (generated by LLM for smart worktrees).
    pub session_name: Option<String>,
    pub delete_branch_after: bool,
    /// Task description for smart worktree (displayed while LLM is generating).
    pub description: String,
    /// When this pending entry was created (for timeout detection).
    pub created_at: std::time::Instant,
    /// Cancellation token: set to `true` to request cancellation of the background thread.
    pub cancel_token: Arc<AtomicBool>,
}

/// Result of a background worktree operation.
#[derive(Debug)]
#[allow(dead_code)]
pub enum WorktreeOpResult {
    Created {
        path: PathBuf,
        pending: PendingWorktree,
    },
    CreateFailed {
        error: String,
        pending: PendingWorktree,
    },
    Deleted {
        branch: String,
    },
    DeleteFailed {
        error: String,
        branch: String,
    },
    Skipped {
        branch: String,
        reason: String,
    },
    /// Smart worktree: LLM resolved a branch name (for UI update).
    SmartBranchResolved {
        description: String,
        branch: String,
        prompt: String,
        session_name: Option<String>,
    },
    /// Smart worktree: entire operation failed.
    SmartFailed {
        description: String,
        error: String,
    },
}

/// Result from the smart worktree LLM generation.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct SmartGenResult {
    pub branch: String,
    pub prompt: String,
    #[serde(default)]
    pub session_name: Option<String>,
}

/// Info about a grabbed branch (branch checkout swap with main).
#[derive(Debug, Clone)]
pub struct GrabbedBranch {
    /// The original branch name (e.g., "feature-x").
    pub branch: String,
    /// Path of the worktree that originally had this branch.
    pub source_worktree: PathBuf,
    /// Claude Code session ID from the source worktree (for resume after grab).
    pub claude_session_id: Option<String>,
}

/// A pending view restore: open this file and scroll to this line once the
/// file tree for the current worktree is loaded. Used to restore where the
/// user was after a restart (or when switching back to a worktree).
#[derive(Debug, Clone)]
pub struct PendingViewRestore {
    /// Worktree-relative path of the file to re-open.
    pub file: String,
    /// Top visible line (0-based) to scroll to.
    pub scroll: usize,
}

/// Tracks which UI panels need re-rendering.
#[derive(Default, Clone, Copy)]
pub struct DirtyPanels(u8);

impl DirtyPanels {
    pub const WORKTREE: u8 = 0b0000_0001;
    pub const EXPLORER: u8 = 0b0000_0010;
    #[allow(dead_code)]
    pub const VIEWER: u8 = 0b0000_0100;
    pub const TERMINAL: u8 = 0b0000_1000;
    pub const ALL: u8 = 0b0000_1111;

    /// All panels dirty — the seed value for a freshly constructed `App` so
    /// every panel renders on the first frame.
    pub fn all() -> Self {
        Self(Self::ALL)
    }

    pub fn mark(&mut self, bits: u8) {
        self.0 |= bits;
    }
    pub fn mark_all(&mut self) {
        self.0 = Self::ALL;
    }
    #[allow(dead_code)]
    pub fn is_dirty(&self, bits: u8) -> bool {
        self.0 & bits != 0
    }
    pub fn any(&self) -> bool {
        self.0 != 0
    }
    pub fn clear(&mut self) {
        self.0 = 0;
    }
}

/// Background operations driven by the 60fps event loop, grouped so that `App`
/// does not carry a separate flat field per async task. Each op is polled from
/// the main loop (or worktree-switch handlers) and writes its result back into
/// the relevant `App` state.
#[derive(Default)]
pub struct BackgroundOps {
    /// Background update check (latest release lookup).
    pub update_check: BackgroundOp<Option<crate::update_checker::UpdateInfo>>,
    /// Background ccusage (token/cost) fetch.
    pub ccusage: BackgroundOp<CcusageInfo>,
    /// Background branch list fetch (switch-branch overlay).
    pub branch: BackgroundOp<Vec<String>>,
    /// Background pull operation.
    pub pull: BackgroundOp<Result<String, String>>,
    /// Background `gh pr view` lookup.
    pub pr_url: BackgroundOp<Option<String>>,
    /// Background diff computation (worktree switch).
    pub diff: BackgroundOp<BgDiffResult>,
    /// Background file tree walk (worktree switch): the root that was walked,
    /// the entries, and the git status snapshot taken alongside them so
    /// `poll_worktree_switch_ops()` can populate `FileTreeEntry::git_state`
    /// without a second `statuses()` call on the main thread.
    ///
    /// 根を結果に含めるのは、走査を始めた時点の選択と、結果が届いた時点の選択が
    /// 一致するとは限らないため。届いたエントリの相対パスを解決できるのは、
    /// それを歩いた根だけ。
    pub file_tree: BackgroundOp<(
        std::path::PathBuf,
        Vec<crate::viewer::FileTreeEntry>,
        crate::git_engine::status_map::GitStatusMap,
    )>,
    /// Background branch details computation (worktree switch).
    pub branch_details: BackgroundOp<git_engine::BranchDetails>,
    /// Background symbol index build.
    pub symbol_index: BackgroundOp<Result<usize, String>>,
    /// Background session-log parse for the reflow transcript view.
    pub reflow_load: BackgroundOp<Vec<crate::claude_log::LogEntry>>,
}

/// Result of a background diff computation.
pub struct BgDiffResult {
    pub committed: Vec<crate::diff_state::FileDiff>,
    pub uncommitted: Vec<crate::diff_state::FileDiff>,
    pub error: Option<String>,
}

/// Aggregated token usage and cost from ccusage.
#[derive(Debug, Clone)]
pub struct CcusageInfo {
    pub total_tokens: u64,
    pub total_cost: f64,
}
